stages:
  create_chunks_from_documents:
    wdir: ../..
    cmd:
      PYTHONPATH=. python scripts/document_ingestion/split_documents_into_chunks.py
      --documents-folder-path data/inputs/documents
      --output-parquet-path data/outputs/chunks/documents_chunks.parquet.gzip
    deps:
      - scripts/document_ingestion/split_documents_into_chunks.py
      - data/inputs/documents
    outs:
      - data/outputs/chunks/documents_chunks.parquet.gzip:
          cache: false
  ingest_embeddings_from_chunks:
    wdir: ../..
    cmd: PYTHONPATH=. python scripts/document_ingestion/ingest_embeddings.py
      --chunks-path data/outputs/chunks/documents_chunks.parquet.gzip
      --selected-vector-db qdrant_local
      --collection-name dvc
    deps:
      - scripts/document_ingestion/ingest_embeddings.py
      - data/outputs/chunks/documents_chunks.parquet.gzip
    outs:
      - data/outputs/qdrant_storage/:
          cache: false
